export {default as Analysis} from './analysis/Analysis'
export {default as HeaderOfIndustries} from './header/Hearder/HeaderOfIndustries'
export {default as OverView} from './overView/OverView'
export {default as Solution} from './solution/Solution'
export {default as Technology} from './technology/Technology'